version: '3'
services:

  postgres:
    image: postgres
    restart: always
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - data:/var/lib/postgres/data
    environment:
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: guacamole_password
      POSTGRES_DB: guacamole_db
    
  guacd:
    image: glyptodon/guacd
    restart: always

  guac:
    image: glyptodon/guacamole
    restart: always
    ports:
      - "8088:8080"
    environment:
      POSTGRES_HOSTNAME: postgres
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: guacamole_password
      GUACD_HOSTNAME: guacd
    
    links:
      - postgres
      - guacd
    
volumes:
  data:
    driver: local
